#!/bin/bash
#  This is a tokenizer special to the CCGB.
#   It "normalizes" words into the form used as keys in db,
#  e.g. all lowercase, no stopwords.
#    So don't use it as a tokenizer for other projects.
#   (This is why it is in libexec and not bin)
#   ONLY CALLED FROM mivec I think

DATAPATH=/usr/local/share/corpas
BDCHARS="A-Za-zÁÉÍÓÚáéíóú"
INTCHARS="'-"

tr -s "[:space:]" "\n" |
sed "
s/[${BDCHARS}][${BDCHARS}${INTCHARS}]*/<c>&<\/c>/g;
s/\([${INTCHARS}][${INTCHARS}]*\)<\/c>/<\/c>\1/g;
" |
sed "
s/<c>/\n/g
s/<\/c>/\n/g
" | grep "[${BDCHARS}]" |
tr "[:upper:]" "[:lower:]" |
grep '..' |
grep -v -x -f ${DATAPATH}/stoplist
