#!/bin/bash

LIBEXECPATH=/usr/local/libexec
MAXHITS=250
MUTATER=cat

xmltohtml()
{
sed -n '
/^<tu>/{
s/.*/<hr>/
p
}
/^<prop.*document.>/{
s/<prop[^>]*>\([^<]*\)<.*/<a href="\/corpas\/ll.html">\1<\/a>:/
p
}
/^<prop.*line.>/{
s/<prop[^>]*>\([^<]*\)<.*/\1<br><br>/
p
}
/^<\/tuv/{
N
s/\n//
s/<\/tuv><tuv.*>/<br><br>/ 
s/<\/tuv><\/tu>/<br>/
p
}
/^<seg>/{
p
}
' |
sed "
/^<seg>/{
s/^<seg>//
s/<\/seg>$//
s/${FILTERED}/<b class=\"gramadoir\">&<\/b>/gI
}
"
}

versionout()
{
	echo "<p>"
	echo "<a href="/corpas/index.html">Corpas Comhthreomhar Gaeilge-Béarla</a>, leagan 0.01<br>"
	echo "Copyright (C) 2004 <a href=\"http://borel.slu.edu/\">Kevin P. Scannell</a><br><br>"
	echo "<i>"
	echo "Is saorbhogearra an ríomhchlár seo; féach ar an bhunchód le haghaidh coinníollacha cóipeála.  Níl baránta AR BITH ann; go fiú níl baránta ann d'INDÍOLTACHT nó FEILIÚNACHT DO FHEIDHM AR LEITH, an oiread atá ceadaithe de réir dlí."
	echo "</i></p>"
}

tmx()
{
echo "$@" | ${LIBEXECPATH}/mivec "${MAXHITS}" "${MUTATER}" | iconv -f iso88591 -t utf8
}

html()
{
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\""
echo "\"http://www.w3.org/TR/html4/strict.dtd\">"
echo "<html lang=\"ga\">"
echo "<head>"
echo "<title>Corpas Comhthreomhar Gaeilge-B&eacute;arla: Tortha&iacute;</title>"
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">"
echo "<link rel=\"stylesheet\" href=\"http://borel.slu.edu/kps.css\" type=\"text/css\">"
echo "</head>"
echo "<body>"
versionout
FILTERED=`echo "$@" | ${LIBEXECPATH}/commontok | tr "\n" "_" | sed 's/_/\\\\\\|/g' | sed 's/^/\\\\\\(/; s/..$/\\\\\\)/'`
echo "$@" | ${LIBEXECPATH}/mivec "${MAXHITS}" "${MUTATER}" | xmltohtml "${FILTERED}"
echo "<hr>"
echo "</body>"
echo "</html>"
}

ACTION=tmx
while [ ${1%%[^-]*} ]
do
	if echo "${1}" | grep "=" > /dev/null
	then
		JUSTOPT=`echo "${1}" | sed 's/=.*//'`
		OPTARG=`echo "${1}" | sed 's/^[^=]*=//'`
		case "${JUSTOPT}" in
		"--max" )
			MAXHITS="${OPTARG}"
		;;
		"--version" | "--html" | "--mutate" )
			echo "Unnecessary argument: ${1}" >&2
			exit 1
		;;
		* )
			echo "Unrecognized option: ${1}" >&2
			exit 1
		;;
		esac

	else
		case "${1}" in
		"--html" )
			ACTION=html
		;;
		"--mutate" )
			MUTATER=/usr/local/bin/mutate
		;;
		"--version" )
			versionout
			exit 0
		;;
		* )
			echo "Unrecognized option: ${1}" >&2
			exit 1
		;;
		esac
	fi
	shift
done
${ACTION} "$@"
